### ISSUE TITLE
copy paste issue

### ISSUE THREAD

**Issue by sirvan-monfared** [ejirocodes/vue3-otp-input#13]
hey there
seems like copy pasting values not reflected on model
so onComplete and onChange are not firing when pasting otp value

**Comment by nimaebra** [comment]
Hi sirvan
I tested the latest version and onComplete fired when pasting OTP value. Can you share your code or explain more about your problem?

**Comment by ejirocodes** [comment]
Thaks a lot @nimaebra,

@sirvan-monfared, you can also try out a watcher


```
watch(pin, (value: string) => {
  if (value.length === 6) {
    disabled.value = false;
  } else {
    disabled.value = true;
  }
});
```

**Comment by 67pankaj** [comment]
@ejirocodes what does pin points to, there is no v-model we only have ref on the component.

**Comment by 67pankaj** [comment]
@ejirocodes what I meant was where do we get/ update the value of pin. Because onComplete doesn't seem to fire when we copy paste the code.

**Comment by ejirocodes** [comment]
@67pankaj, what version are you using, can you set up a sandbox or install an earlier version

**Comment by 67pankaj** [comment]
using version 0.3.6

this is the code : 

```
<v-otp-input
      ref="otpInput"
      class="otp-inputs-wrapper row no-wrap items-center"
      input-classes="otp-input"
      :num-inputs="6"
      :placeholder="['0', '0', '0', '0', '0', '0']"
      :is-input-num="true"
      separator=""
      @on-change="handleOnChangeOtp"
      @on-complete="handleOnCompleteOtp"
    />
```

```
const isOtpComplete = ref(false);

function handleOnChangeOtp(value) {
  // value represents the single digit input
  isOtpComplete.value = false;
}
function handleOnCompleteOtp(value) {
  // value represents the complete 6 digit otp
  isOtpComplete.value = true;
}
```

how do I get the updated value everytime something is changed

**Comment by ejirocodes** [comment]
@67pankaj, it's written in the docs [here](https://github.com/ejirocodes/vue3-otp-input#13-register-as-a-vue-component-locally-or) and also the example [here](https://github.com/ejirocodes/vue3-otp-input/blob/main/dev/serve.vue#L10), you're not doing anything with the value parameters at the moment
