### ISSUE TITLE
0.3.5 版本在vue3+vite中打包错误

### ISSUE THREAD

**Issue by mengkong123** [ejirocodes/vue3-otp-input#17]
![image](https://user-images.githubusercontent.com/18375661/170714922-bc24d002-568b-4b4b-a0ed-738dcb7289fc.png)

**Comment by Gerolmed** [comment]
I can confirm that the latest package is empty:
![image](https://user-images.githubusercontent.com/19486712/170825706-c4c48d88-f107-4553-a623-7959bfb7328a.png)

**Comment by ejirocodes** [comment]
@Gerolmed please install an older version for now

**Comment by ejirocodes** [comment]
This has been fixed @Gerolmed @mengkong123
