### ISSUE TITLE
Set optional value to handleOnBlur

### ISSUE THREAD

**Issue by rodrigoUriarte** [ejirocodes/vue3-otp-input#23]
Hi there

I'm trying to implement this nice component on a project. The problem I'm facing is that my inputs are coming from a virtual component keyboard, so when I click on one of my buttons on the virtual keyboard this function is triggered.
` 
const handleOnBlur = () => {
      activeInput.value = -1;
};
`
So the otp input is never filled. I'm wondering if this onblur behavior can be optional for cases like this?

Also I'm facing that I have to call method `pin.value.handleOnChange(value);` to fill the inputs from this virtual keyboard. Maybe we can expose this method as a prop in the <v-otp-input> component like the @on-complete.

**Comment by ejirocodes** [comment]
@rodrigoUriarte, It is hard for me to understand what you actually want to accomplish.  I would appreciate it if you could set up a sample project for me to look at. Thanks

**Comment by rodrigoUriarte** [comment]
Nevermind I have replaced with a simple text input for this case.
