### ISSUE TITLE
Security Mode

### ISSUE THREAD

**Issue by qertis** [ejirocodes/vue3-otp-input#24]
Props

secure | boolean | false | Display * instead of character
-- | -- | -- | --

**Comment by ejirocodes** [comment]
Hi @qertis, I'm not sure I understand what you are suggesting 🤔

**Comment by qertis** [comment]
> Hi @qertis, I'm not sure I understand what you are suggesting 🤔 

Hi. It is a secure mode for the PIN. See example:

This is standard mode: 
![image](https://user-images.githubusercontent.com/3893228/184701579-fff5ee87-a456-4b7c-8156-81b1b35051c7.png)

This is a secure mode:
![image](https://user-images.githubusercontent.com/3893228/184701640-9401a52d-1a93-4902-983a-41bf0b815e3f.jpeg)

**Comment by ejirocodes** [comment]
@qertis

that's what the `input-type` prop of password is for. See the [docs](https://github.com/ejirocodes/vue3-otp-input#-props
)
