### ISSUE TITLE
`SingleOtpInput` pattern should change based on the `input-type` prop

### ISSUE THREAD

**Issue by sybrendotinga** [ejirocodes/vue3-otp-input#27]
**Describe the bug**
The Pattern of the `SingleOtpInput` should change based on the `input-type` prop. `letter-numeric` should allow `a-zA-Z` as well.

**To Reproduce**
Make a component with `input-type` letter-numeric` and type a OTP code that includes letters. The input will become invalid. 
See: https://github.com/bachdgvn/vue-otp-input/blob/develop/src/components/SingleOtpInput.vue#L10

**Expected behavior**
The `letter-numeric` should allow the pattern `0-9a-zA-Z`. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/14016492/205666050-b65f9b75-d665-4a68-ba6b-5e2dcfeb3b0b.png">

**Comment by escapedcat** [comment]
@sybrendotinga kinda stumbled across the same "issue".  

In our case we can get around this by using novalidate, i.e.
```vue
<form
    style="display: flex; flex-direction: row"
    novalidate
    @submit.prevent="handleSubmit"
  >
     <v-otp-input... />
     <button type="submit">Submit</button>
</form>
```

Not sure about your usecase and how you do validation though.

**Comment by ejirocodes** [comment]
@sybrendotinga, please open a new issue if the solution from @escapedcat doesn't address your issue
