### ISSUE TITLE
Docs mention `is-input-num`, should be `input-type`

### ISSUE THREAD

**Issue by sybrendotinga** [ejirocodes/vue3-otp-input#28]
**Is your feature request related to a problem? Please describe.**
Docs mention `is-input-num`, but this should be `input-type` (with a valid type)
https://github.com/ejirocodes/vue3-otp-input#23-use-the-registered-component-in-your-vue-template

**Describe the solution you'd like**
Update docs to reflect the proper implementation

**Describe alternatives you've considered**
I've looked at the source directly

**Comment by ejirocodes** [comment]
Hi @sybrendotinga, this has been fixed in the latest update
