### ISSUE TITLE
input onchanged class

### ISSUE THREAD

**Issue by jiexaspb** [ejirocodes/vue3-otp-input#33]
Hello

I would like to add a class to the input when a number is entered in this input. For example, I want to add a bounce class so that a digit input has a ripple effect when the digit is added.

Could you add such a parameter?

**Comment by ejirocodes** [comment]
@jiexaspb 
see this [section](https://github.com/ejirocodes/vue3-otp-input#33-optional-some-basic-styling-options). There's a class added when an input is filled. So you could have something like 

`input.otp-input.is-complete:focus`

<img width="535" alt="image" src="https://user-images.githubusercontent.com/45228014/230434822-f14d0d6e-390e-4835-8e68-ef150b1fa611.png">

Let me know if this solves it for you

**Comment by ejirocodes** [comment]
@jiexaspb, I'll close this for now. Please open a new issue if it still occurs
