### ISSUE TITLE
When user start typing from right to left it is duplicating the value when using v-model

### ISSUE THREAD

**Issue by aakashbathla** [ejirocodes/vue3-otp-input#34]
**Describe the bug**
When user start typing from right to left, it is duplicating the value and also autfocus is not working as expected

**To Reproduce**

Instead of going from left to right. I tried going from right to left. 
suppose i have 6 input fields and i directly typed in 6th field. it is duplicating the value in first too.

for 5th it is duplicating the value in 2nd. 

**Expected behavior**
should not duplicate values

**Comment by alex-maereanu** [comment]
I can confirm this bug

**Comment by ejirocodes** [comment]
Fixed and publish #42
