### ISSUE TITLE
Feature: show/view functionality when using `input-type="password"`

### ISSUE THREAD

**Issue by escapedcat** [ejirocodes/vue3-otp-input#40]
**Is your feature request related to a problem? Please describe.**
Sometimes a user wants to see the input.  
It would be nice to have a method to hide/show the input.

**Describe the solution you'd like**
I.e. when using `input-type="password"` to offer a method which toggles inputs between `type="text"` and `type="password"`.

We could create a PR if this is wanted.

**Comment by escapedcat** [comment]
Yes, happy to give it a try. Would not do it now but when I get to it if that's ok.

**Comment by ejirocodes** [comment]
Merged and published here #38
