### ISSUE TITLE
Event API is deprecated

### ISSUE THREAD

**Issue by wutkaru** [ejirocodes/vue3-otp-input#44]
'which' is deprecated
Link: [see more](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which)
'keyCode' is deprecated
Link: [see more](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

<img width="611" alt="image" src="https://github.com/ejirocodes/vue3-otp-input/assets/43336971/7ee9eb3b-7b4b-44cc-a166-53ac61aa5c3b">

**Comment by busybox11** [comment]
What?

**Comment by ejirocodes** [comment]
@wutkaru, please would you want to submit a PR for this issue?
