### ISSUE TITLE
Methods for inserting values programmatically

### ISSUE THREAD

**Issue by 0ip** [ejirocodes/vue3-otp-input#6]
Hello Ejiro,
Thank you for making this component.

In my application I would like to be able to use a virtual keyboard with which the OTP is entered. But this would require methods to update the OTP programmatically, like `updateCurrentFocusValue(3)` or maybe `updateValueAt(0, 3)`.

**Comment by ejirocodes** [comment]
Hi @0ip, were you able to get this done?

**Comment by 0ip** [comment]
Thank you for your response. There's no need for that feature anymore in my project.
