### ISSUE TITLE
Pre-fill inputs

### ISSUE THREAD

**Issue by ishaiavrahami** [ejirocodes/vue3-otp-input#7]
Hello is it possible to pre-fill the inputs?

Perhaps v-model ?

**Comment by ejirocodes** [comment]
@ishaiavrahami where will the value of the input coming from in this case 🤔

**Comment by ishaiavrahami** [comment]
It would come from the data.. same as v-model

**Comment by ejirocodes** [comment]
Oh I get. That feature isn't available at the moment. It will take some refactoring to implement this

**Comment by arnoldtkl** [comment]
🤔 I just wondering why need a pre-fill input, under what use case needed this feature?

**Comment by ishaiavrahami** [comment]
Imagine you want your user to change is current password. Or you want your user to see that he already has a password set..

**Comment by ejirocodes** [comment]
This #30 pr should address this

**Comment by ejirocodes** [comment]
@ishaiavrahami, @arnoldtkl this has been fixed thanks to @Gemerz
