### ISSUE TITLE
[Help] Styling issue

### ISSUE THREAD

**Issue by arnoldtkl** [ejirocodes/vue3-otp-input#8]
Hi, thanks for maintaining this component. 

I just import this component inside my vue file, but the page display as follow:

![Untitled](https://user-images.githubusercontent.com/6742498/163946207-b6b3dd3f-3115-48aa-a0a8-83c70e26f1ee.jpg)

I following the code example that you wrote in the readme, beside that, I purposely set the height and width to 1px, the component don't have any effect. Can you please guide me how to resolve the box sizing issue? 

FYI, I imported your component in my[ quasar framework](https://quasar.dev/) project. Is that possible your component styling will crash with the framework? Any advice will be appreciated, thank you again 😄

**Comment by arnoldtkl** [comment]
I just found that is my style tag issue. I will close this issue.

**Comment by tintin10q** [comment]
Could you say more about what you changed to fix this. I have the same issue. 


I have:

```html
 <p>Hi the code has been sent</p>
<div class="flex">
<v-otp-input
              ref="otpInput"
              input-classes="otp-input"
              separator="-"
              :num-inputs="2"
              inputmode="numeric"
              :should-auto-focus="true"
              :is-input-num="true"
              @on-change="handleOnChange"
              @on-complete="handleOnComplete"
/>
<button @click="clearInput()">Clear Input</button>
</div>
```

```vue
<script lang="ts" setup>
const otpInput = ref({})

const handleOnComplete = (value: string) => {
  console.log('OTP completed: ', value);
};

const handleOnChange = (value: string) => {
  console.log('OTP changed: ', value);
};

const clearInput = () => {
  // @ts-ignore
  otpInput.value.clearInput()
}


</script>

<script lang="ts">
import {defineComponent} from "vue";
import VOtpInput from 'vue3-otp-input';

export default defineComponent({
  name: "phone", components: {VOtpInput},
});
</script>
```

But it looks like this:

![image](https://user-images.githubusercontent.com/24190849/165091923-0872d8fe-d8a1-4948-81c0-4d09143509bb.png)

It seems like some css is not loading. I tried to remove all the <style></style> from my .vue file but that did not change anything.   I also use the .otp-input that you suggested but that also did not work. Please help

**Comment by ejirocodes** [comment]
@tintin10q, add [this](https://github.com/ejirocodes/vue3-otp-input#33-optional-some-basic-styling-options)  (without scoped attribute)

**Comment by tintin10q** [comment]
I just came back to say that I found that scoped was the issue. Thank you. Maybe it is good to add an extra sentence in the readme about this? Something like: Note: This css has to go into a <style> tag which does not have scoped. 

Also I just learned a .vue file can have multiple style tags so you can have one which is not scoped and one which is.
